version: '3'  
services:
  azurefunctionslocal:
    image: tolbargy/azurefunctionslocal
    container_name: azurefunctionslocal
    environment:
      drontestbus_SERVICEBUS: ${drontestbus_SERVICEBUS}
      AzureWebJobsStorage: ${AzureWebJobsStorage}
    build: 
      context: ./
    ports:  
    - "8080:80"